-- Legacy PostgreSQL extension bootstrap retained for reference during the
-- Postgres-to-SQLite cutover. Runtime schema initialization now lives in
-- libs/db/bootstrap.py and does not execute this file.
